//! Atomic claims for `cargo-lid-rs`, one file per slice: a slice's claims
//! are the specs registered from `src/spec/<slice>.rs`, which is how
//! `phase-check 5` finds them (`docs/intent/phase/lld.md`).

mod cargo_lid_rs;
mod coach;
mod headless_canopy_agent;
mod init;
mod lld_review;
mod phase;
mod sync;

pub use cargo_lid_rs::{
    CargoInsertedSubcommandNameIsDiscarded,
    UnknownSubcommandsFailWithUsage,
    TheProjectRootComesFromCargoMetadata,
    MutationScopeFallsBackFromWorkspaceToPackageToDiff,
    ScopeFlagsOverrideTheConfiguredScope,
    DiffScopePassesThroughToTheEngine,
    ValidationEdgesComeFromTheOwningCrateTestBinary,
    MembersWithoutALibraryTargetAreSkipped,
    TracedMutantsRunOnlyTheirValidatingTests,
    UntracedMutantsFallBackToModuleTests,
    SurvivingMutantsFailTheGate,
    AMutantsVerdictComesFromItsOwnGroupsRun,
    AnEngineRunWithoutAVerdictIsAFailure,
    EveryGroupRunsBeforeSurvivorsAreReported,
};

pub use coach::{
    TheCoachsSliceIsTheFlagsValueOrTheBranchName,
    TheDoorDefaultsToCanopysProductionDoor,
    TheMaxCostDefaultsToFive,
    AnyOtherArgumentToCoachIsRejectedByName,
    PackageAndWorkspaceRefuseEachOther,
    NeitherFlagSettlesOnNoTarget,
    APackageNamingAMemberIsThatMembersManifestDirectory,
    APackageNamingNoMemberStopsTheRunListingTheMembers,
    TheWorkspaceFlagNamesTheWorkspaceRoot,
    NoTargetInAOneMemberWorkspaceIsThatMembersDirectory,
    NoTargetInAWorkspaceOfSeveralMembersStopsNamingTheFlag,
    TheDocumentIsTheSlicesLldUnderThatDirectory,
    TheDocumentsPathIsPrintedWhenTheSessionOpens,
    TheArtifactChecksRunOnceBeforeTheFirstQuestion,
    AnUnreadableGuidelineStopsTheRunNamingItsPath,
    ADriftedChecklistIsReportedAndTheInterviewProceeds,
    AReaderDeclaringTooManyToolsIsReportedAndTheInterviewProceeds,
    TheSystemPromptIsTheSyncedInterviewMethodThenTheGuideline,
    TheOpeningNamesTheSlice,
    AnExistingDocumentIsReadWholeIntoTheOpeningAsAnAmendment,
    TheOpeningLeadsWithWhatTheRepositoryHolds,
    ThePreambleIsTheIndexTheHldThenTheGuidance,
    TheIntentIndexNamesEveryIntentDocumentInTheWorkspace,
    TheIntentIndexIsSortedSoTwoRunsAgree,
    EveryIndexRowNamesItsDocumentRelativeToTheWorkspaceRoot,
    ThisRunsOwnDocumentIsMarkedInTheIndex,
    TheDocumentsTheIndexNamesAreNamedAndNotCarried,
    TheOpeningCarriesTheSoleHldWhole,
    AnIndexWithoutExactlyOneHldCarriesNoHld,
    TheProjectsGuidanceIsTheWorkspacesAgentsFileWhole,
    ClaudeMdIsTheGuidanceWhenThereIsNoAgentsFile,
    NeitherGuidanceFileCarriesNoGuidance,
    TheCoachDeclaresExactlyTheReadGrepDraftAndAskTools,
    ReadAndGrepAreDeclaredWithTheCanopyClientsSchemas,
    EverySessionTheCoachOpensIsDialledWithTheMaxCost,
    TheFirstTurnSettlesOnTheOpeningBeforeTheHumanIsRead,
    TheModelsSettledAnswerIsPrinted,
    TheConversationEndsAtDoneOrEndOfFile,
    TheCoachingSessionIsStoppedBeforeTheClientExits,
    ThatATurnDraftedIsRecordedByTheExecutorNotInferred,
    TheJudgesAnswerATurnThatDrafted,
    AFailedDraftIsNotATurnThatDrafted,
    ATurnThatDraftedNothingIsAnsweredByTheHuman,
    TheJudgesAnswerAtMostOneDraftingTurnInARow,
    AHaltReachingTheLoopEndsTheConversationWithItsSentence,
    TheDraftedDocumentSurvivesAHalt,
    TheCoachingSessionsNarratorPrintsTheModelsText,
    EveryToolCallIsAnnouncedBeforeItIsRouted,
    AReadIsAnnouncedByThePathItNames,
    AGrepOrGlobIsAnnouncedByThePatternItNames,
    ADraftIsAnnouncedByTheDocumentItReplaces,
    AskAnnouncesNothing,
    ACallWhoseArgumentsLackItsSubjectAnnouncesNothing,
    AReaderSessionsToolCallsAreAnnouncedToo,
    AReaderSessionNarratesNothing,
    AnOpTheCoachDidNotDeclareIsRefusedWithItsName,
    AReadIsRoutedToTheCanopyClientsReadOverItsConfinement,
    AGrepIsRoutedToTheCanopyClientsGrepOverItsConfinement,
    DraftReplacesTheDocumentWholeCreatingItsDirectory,
    DraftWritesTheSlicesLldAndNoOtherPath,
    DraftAnswersWithThePathAndTheBytesWrittenNotAVerdict,
    AskPutsItsQuestionToTheHumanAndAnswersWithWhatTheyTyped,
    TheStallWindowIsPrintedOnceBesideTheQuestion,
    EndingTheConversationInsideAskIsAToolError,
    AConversationEndedInsideAskEndsTheLoopWhenTheTurnSettles,
    TheJudgesTurnIsTheDocumentChecksThenTheReader,
    TheDocumentChecksRunOverThePathDraftWrote,
    AJudgingWhoseChecksAllHeldSaysSo,
    TheArtifactChecksAreNotInTheJudgesTurn,
    AJudgingsVerdictIsTheFourDocumentChecksAndNothingElse,
    TheHumanIsToldHowTheDocumentChecksFoundTheDocument,
    AnUnreadableDocumentsSentenceIsLandedInPlaceOfTheChecksFailures,
    AnUnreadableDocumentIsToldToTheHuman,
    AnUnreadableDocumentsVerdictIsThatTheChecksDoNotHold,
    ADocumentThatCannotBeReadBackDoesNotEndTheConversation,
    TheReadersSystemIsTheSyncedReaderBody,
    AReaderSessionDeclaresTheCanopyClientsObservationTools,
    AReaderSessionCarriesNoPhase,
    AReaderTurnIsRunByTheCanopyClientsOwnDispatch,
    TheJudgingsHeadingIsPrintedBeforeAReaderSessionOpens,
    TheReaderIsAFreshSessionForEveryJudging,
    TheReaderIsGivenTheDocumentAndAskedForFindings,
    AReaderSessionIsStoppedWhenItAnswers,
    AFailedReadersSentenceIsLandedInPlaceOfItsFindings,
    AFailedReaderIsToldToTheHuman,
    AReaderThatCannotBeConsultedDoesNotEndTheConversation,
    TheDocumentChecksAreLandedWhetherOrNotTheReaderAnswers,
    TheJudgesAreLandedAsOneUserMessageUnderAHeading,
    TheEndingPrintsThePathAndWhetherTheChecksHold,
    TheEndingNamesThePhaseOneCommitTheCoachDoesNotMake,
    ARunThatDraftedNothingEndsSayingSo,
};

/// The name [`TheCoachDeclaresExactlyTheReadGrepDraftAndAskTools`] carried
/// while the coach's tool set was three. The alias registers no claim, so the
/// graph sees only the claim it points at; every citation of this name warns
/// with its replacement, and those citations are the later phases' work list.
#[deprecated = "replaced by TheCoachDeclaresExactlyTheReadGrepDraftAndAskTools"]
pub type TheCoachDeclaresExactlyTheReadDraftAndAskTools = coach::TheCoachDeclaresExactlyTheReadGrepDraftAndAskTools;

pub use headless_canopy_agent::{
    CanopyTakesSliceDoorAndMaxCostAsItsFlags,
    TheKeyComesFromCanopyKeyOrTheRunStopsFirst,
    TheKeyIsPresentedOnlyToTheDoor,
    EveryPhasePrintsItsSessionsAndItsEnding,
    TheLastLineIsTheTerminalStateAndTheExitStatusFollowsIt,
    PrReadyEndsWithTheBranchAndEveryRecordedDecision,
    ThePreconditionNeedsTheSliceBranchCheckedOut,
    ThePreconditionNeedsAPhaseOneCommit,
    ThePreconditionNeedsACleanTree,
    CommittedPhasesAreReadFromTheSubjectTags,
    ACompileTimeSliceStopsAtThePreconditionWithoutAcceptance,
    CommittedPhasesAreSkippedAndSaidSo,
    ThePhasesAreOneSessionEachInOrder,
    TheDialCarriesExactlyFourSettings,
    MaxCostIsTheFlagsAmountOrFive,
    AConfigThatPinsADialledSettingStopsTheRunNamingIt,
    NoPolicyRecordIsLandedAfterTheDial,
    TheClientCallsOnlyTheConverseExecuteAndStopFaces,
    TheSystemPromptIsTheSyncedAgentBodyWithoutItsFrontmatter,
    TheWorkerPolicyAdmitsExactlyTheFiveTools,
    TheWorkerPromptCarriesTheSliceTheLogAndTheSubject,
    AReworkPromptCarriesTheReviewersFindings,
    EverySessionIsStoppedWhenItsPhaseEnds,
    APolicyIsBuiltFromTheDeclarationsItsHostHands,
    ASessionCarriesTheDeclarationsItsHostDialled,
    APairedForwardRunsThroughTheExecutorTheTurnWasHanded,
    ThePreCallTextOfAToolAskingResponseGoesToTheNarrator,
    ASettlingResponsesTextIsNotNarrated,
    AResponseThatCarriedNoTextNarratesNothing,
    ThisHostDrivesEveryTurnWithTheSilentNarrator,
    ASessionWithoutAPhaseAsksNoPreToolVerdict,
    ASessionWithoutAPhaseKeepsNoTally,
    AForwardsOpClassifiesToItsToolOrToNone,
    EveryToolConfinesItsPathToTheWorkspace,
    ReadReturnsNumberedLinesOrADirectorysEntries,
    GrepIsALiteralSubstringSearchCappedAtTwoHundredLines,
    GlobReturnsMatchingPathsSorted, AGlobPatternIsConfinedAndItsMatchesStayUnderTheRoot,
    EditReplacesTheOneOccurrenceOrAllOnRequest,
    AnAmbiguousOrAbsentOldStringIsAnErrorNamingTheCount,
    WriteCreatesOrReplacesTheFileWhole,
    ObservationsAreTalliedThroughThePreToolVerdict,
    ARefusedEditIsTheToolsErrorAndTheFileIsUntouched,
    AnAllowedEditReturnsThePostEditVerdictsText,
    TheReviewerPolicyAdmitsOnlyTheObservationTools,
    AnEditForwardedToTheReviewerIsRefusedHere,
    TheTailIsFollowedByParkedReadsWithinTheCredentialsLife,
    AForwardIsPairedWithTheHeldPayloadOfItsDigest,
    AForwardToAnotherPrincipalIsNotAnswered,
    ThePayloadDigestReproducesCanopysVector,
    CanonicalJsonOrdersKeysByByteAndRendersNumbersAsF64,
    ACompletionAnswersThePayloadsProducer,
    ACompletionsIdempotencyKeyIsTheForwardsCursor,
    ADenialIsCountedAsARefusal,
    ATurnSettlesOnAResponseWithoutToolUses,
    AProviderTerminalIsRetriedOnceThenStopsTheRun,
    AHaltEndsTheRunWithItsReason,
    AQuietTailForFifteenMinutesStopsTheRun,
    TheCredentialIsRefreshedBeforeItExpires,
    ADoorRefusalStopsTheRunWithItsSentence,
    AShedIsWaitedOutAndTheSameRequestSentAgain,
    AShedsPauseIsItsRetryAfterSeconds,
    AMissingOrUnreadableRetryAfterPausesFiveSeconds,
    TheFourthShedIsARefusalLikeAnyOtherStatus,
    EveryStatusButAShedIsRefusedOnItsFirstAnswer,
    ARetriedSendCarriesTheFirstAttemptsIdempotencyKey,
    TheSettledTextGoesToTheStopVerdictAsTheSession,
    ARefusedStopIsLandedAsTheNextUserMessage,
    TheNinthConsecutiveRefusalEndsTheRun,
    AWorkersStopBlockEndsTheRunWithItsDecisions,
    TheCommitNamesItsSessionAsTheAgent,
    EveryCommittedPhaseIsReviewedBeforeTheNextOpens,
    TheReviewPromptNamesTheCommitTheLldAndTheSkillFiles,
    TheReviewBlockParsesToApprovedOrFindings,
    ARejectionWithAReworkLeftOpensAnotherWorkerSession,
    TheReworkBudgetIsOnePoolOfSixAcrossEveryPhase,
    AReworksCommitIsAnotherPhaseCommitOnTheBranch,
    AReworksCommitIsReviewedByAFreshSession,
    ARejectionWithTheBudgetSpentEndsTheRunWithTheFindings,
    AnExhaustedBudgetIsSaidToBeWhatStoppedTheRun,
    AMissingReviewBlockIsAskedForOnceMore,
    ASecondMissingReviewBlockIsARejection,
};

pub use init::{
    InitTargetsThePackageInTheCurrentDirectory,
    InitWritesNothingWhenAnyTargetConflicts,
    InitAddsLidRsAtTheToolsOwnVersion,
    InitAppendsTheManifestTables,
    InitWiresTheLibraryIntoTheGraph,
    BinOnlyPackagesGainALibrary,
    EmittedFilesCarryThePackageFacts,
    MutationOutputIsIgnoredWithoutConflict,
    AnInitialisedPackagePassesItsOwnGate,
    NewCreatesALibraryPackageThenInitialisesIt,
};

pub use lld_review::{
    TheSliceIsTheFlagsValueOrTheBranchName,
    AnyOtherArgumentIsRejectedByName,
    TheDocumentIsTheSlicesLldUnderThePackageThatHoldsIt,
    AWorkspaceOnlySlicesDocumentIsAtTheWorkspaceRoot,
    AnUnreadableLldFailsNamingItsPath,
    LldCheckExitsZeroOnlyWhenEveryCheckHolds,
    EveryFailureIsReportedNotOnlyTheFirst,
    AFailureNamesItsCheckItsFileItsLineAndItsRule,
    ATableIsTheRowsUnderItsHeadingLessHeaderAndSeparator,
    ADocumentWithoutADecisionsTableFails,
    EveryDecisionsRowFillsItsFourCells,
    EveryShapeRowNamesAnIdentifierAndARole,
    ADocumentWithNoShapeTableHoldsThatCheck,
    EveryDeferredItemIsANumberedListItem,
    ADocumentWithNoDeferredHeadingHoldsThatCheck,
    EveryCheckIsNamedInTheGuidelinesChecklist,
    TheReaderDeclaresOnlyTheObservationTools,
    AnArtifactFailureWithNoLineToCitePointsAtTheFirstLine,
    TheArtifactChecksRunWhateverSliceIsNamed,
    AnUnreadableSyncedArtifactFailsNamingItsPath,
};

pub use phase::{
    PhasesWithoutACommitHaveNoCheck,
    PhaseOneChecksTheDocs,
    PhaseTwoChecksTheClaimsBuild,
    WarningsDoNotFailPhaseTwosCheck,
    PhasesThreeAndFourCheckTheSkeletonTypeChecks,
    PhaseSevenRunsTheGateInOrder,
    ACheckStopsAtTheFirstFailingStep,
    ASlicesClaimsAreTheSpecsInItsSpecFile,
    TheSliceComesFromTheBranchName,
    ASliceWithNoClaimsFailsTheRedCheck,
    TheBaseIsTheNewestGateCommitReachableFromHead,
    TheRedSetIsTheClaimsAddedSinceTheBase,
    AFreshSliceHasEveryClaimInTheRedSet,
    AnEmptyRedSetAfterAGateFailsTheRedCheck,
    EveryClaimNeedsAValidationBeforePhaseFivePasses,
    EachValidationRunsAloneByExactName,
    AGreenValidationFailsTheRedCheck,
    TheSlicesCrateIsTheOneHoldingItsLld,
    PhaseTwoMayWriteOnlyTheSlicesSpecFiles,
    PhasesThreeAndFourMayWriteTheSliceModuleAndTheLibraryRoot,
    PhasesFiveAndSevenMayWriteOnlyTheSliceModule,
    PathsOutsideTheSlicesCrateAreRefusedBeforeThePolicy,
    ARefusedEditQuotesTheDisciplineRow,
    ReadsAreNeverRefused,
    EveryToolCallIsTallied,
    EveryEditIsFollowedByClippy,
    AFinalMessageCarriesExactlyOneEnding,
    AStopBlockEndsThePhaseWithoutACommit,
    ACommitSubjectMustCarryThisPhasesTag,
    ACommitBlockRunsThePhasesCheck,
    ARefusalCarriesTheOutputTheRuleAndThePermittedMoves,
    AFailingOutputNamesItsCheck,
    SyncedArtifactsMustMatchAtTheStop,
    ChangesOutsideThePolicyRefuseTheStop,
    OnlyThePoliciesPathsAreStaged,
    NothingToCommitIsARefusal,
    TheTallyIsWrittenAsTrailers,
    ACompileTimeSliceIsDisclosed, ACompileTimeSliceNeedsTheHumansAcceptance,
    SyncMirrorsEveryArtifactTheDependencyShips,
};

/// The name [`PhaseTwoChecksTheClaimsBuild`] carried while phase 2's check
/// also linted. The alias registers no claim, so the graph sees only the
/// claim it points at; every citation of this name warns with its
/// replacement, and those citations are the later phases' work list.
#[deprecated = "replaced by PhaseTwoChecksTheClaimsBuild"]
pub type PhaseTwoChecksTheClaimsBuildAndLint = phase::PhaseTwoChecksTheClaimsBuild;

pub use sync::{
    TheSkillComesFromTheResolvedLidRsDependency,
    TheSkillCopyLivesAtTheWorkspaceRoot,
    SyncCheckFailsOnAnyDifferenceAndWritesNothing,
    AMissingSkillSourceFailsByName,
};
